const PDFDocument = require('pdfkit');
const fs = require('fs');

class PDFGenerator {
  static generateReport(test) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50 });
        const filename = `/tmp/report-${test.testCode}.pdf`;
        const stream = fs.createWriteStream(filename);

        doc.pipe(stream);

        // Header
        doc
          .fontSize(28)
          .font('Helvetica-Bold')
          .text('Email Deliverability Report', { align: 'center' });

        doc.fontSize(12).font('Helvetica').text(`Test Code: ${test.testCode}`, {
          align: 'center',
        });

        doc.fontSize(10).text(`Generated: ${new Date().toLocaleString()}`, {
          align: 'center',
        });

        doc.moveTo(50, doc.y + 10).lineTo(550, doc.y + 10).stroke();
        doc.moveDown(2);

        // Score
        doc
          .fontSize(18)
          .font('Helvetica-Bold')
          .text(`Deliverability Score: ${test.deliveryScore}%`, {
            align: 'center',
          });

        doc
          .fontSize(11)
          .font('Helvetica')
          .text(
            `${test.results.filter(r => r.received).length} of ${test.results.length} inboxes`,
            { align: 'center' }
          );

        doc.moveDown(2);

        // Results Table
        doc.fontSize(14).font('Helvetica-Bold').text('Results by Provider:');
        doc.moveDown(1);

        const tableTop = doc.y;
        let i = 0;

        test.results.forEach(result => {
          const yPosition = tableTop + i * 30;

          doc
            .fontSize(11)
            .font('Helvetica-Bold')
            .text(result.provider, 60, yPosition);

          doc
            .fontSize(10)
            .font('Helvetica')
            .text(
              result.received
                ? `✓ Received in: ${result.folder}`
                : '✗ Not Received',
              250,
              yPosition,
              { color: result.received ? '#22c55e' : '#ef4444' }
            );

          i++;
        });

        doc.moveDown(5);
        doc
          .fontSize(9)
          .font('Helvetica')
          .text(
            'This report was generated by Email Spam Report Tool. Test results are based on IMAP inbox checks.',
            { align: 'center', color: '#666' }
          );

        doc.end();

        stream.on('finish', () => resolve(filename));
      } catch (err) {
        reject(err);
      }
    });
  }
}

module.exports = PDFGenerator;